---
title: '2019-05-15'
author: "Tony"
date: "2019年5月15日"
output: html_document
---

```{r}
Vector1 <- letters[1:6]
Vector1

names(Vector1)
```


```{r}
names(Vector1) <- c('名稱1','名稱2','名稱3','名稱4','名稱5','名稱6')
names(Vector1)
```

```{r}
names(Vector1)[[2]]

```

#colnames

```{r}
StuDF2 <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50),
  stringsAsFactors = FALSE
  )
StuDF2 
```


```{r}
colnames(StuDF2) 
rownames(StuDF2)
```

```{r}
colnames(StuDF2) <- c("ww","oo","kk")
colnames(StuDF2)
StuDF2
```
#若只改一個
```{r}
colnames(StuDF2)[[3]] <- c("哈")
colnames(StuDF2)
StuDF2
```
#若改兩個
```{r}
colnames(StuDF2)[c(1,2)] <- c("了","屋")
colnames(StuDF2) 
StuDF2
```

#改元素
```{r}
b <- list(
  元素1=1,
  元素2="Hello",
  元素3=TRUE
)

b$元素3 <- FALSE
b[[5]] <- 7
b

```
#創新元素
```{r}
names(b)
b[["新元素A"]] <- c(1,2,3)
b$新元素B <- c(T,F,T)
b
```
#practice
```{r}
library(readr)
exData3 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData3.csv",
                    col_types = cols(
                      匯率 = col_number(),
                      期間 = col_character()))
```
```{r}
library(lubridate)
```

#取出「期間」變數轉成date class
```{r}
exData3$期間 -> date1
date2 <- ymd(date1)
exData3$期間 <- c(date2)
exData3

```

#增加一個「isAsiaCrisis」的logical變數，其值為TRUE若「期間」介於1997-06-01到1998-12-01（含前後）。
```{r}
www <- ymd("1997-06-01")
qqq <- ymd("1998-12-01")
isAsiaCrisis <- exData3$期間 >= www & exData3$期間 <= qqq
isAsiaCrisis
```
#利用「isAsiaCrisis」值，結合使用[.R,.C]取出1997-06-01到1998-12-01亞洲金融危機的子樣本
```{r}
exData3[isAsiaCrisis,]
```
#8.1.2 practice 
```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
transcriptDataFinal
```
#選出“92aS67fee”的子樣本
```{r}
awsd <- transcriptDataFinal$學號=="92aS67fee"
transcriptDataFinal[awsd,]
```

#8.1
```{r}
utility_cobb_douglass <- function(x,y,.alpha,.beta){
  utilValue <- x^.alpha*y^.beta # 程序產生output值
  return(utilValue) # 傳回output值
}
```

```{r}
class(utility_cobb_douglass)
utility_cobb_douglass(1.456,2.434,0.534,0.8321)
```

```{r}
ya <- function(x,y,z,r){
  sda1 <- x^z*z^y*y*r/x^6.784
return(sda1)
}
ya(6.6879,7.932,8.58302,9.4328)
```

```{r}
demand_fun <- function(a,b,P){
  Qd <- a+b*P
  return(Qd)
}
supple_fun  <- function(c,d,P){
  Qs <- c-d*P
  return(Qs)
}
demand_fun (2,3,4)
supple_fun(1,1.2,3)
```

