---
title: '2019-06-12'
author: "Tony"
date: "2019年6月12日"
output: html_document
---
#Sequance
```{r}
load(url("https://www.dropbox.com/s/duh5aaqgl2f5m3z/loopTranscriptData.Rda?raw=1"))
studentIds <- unique(transcriptDataFinal$學號) # 全部可能學號
studentIds5 <- studentIds[1:5] # 前5筆學號
```

```{r}
for(i in seq_along(studentIds5)){
  print(studentIds5[[i]])
}
```
#範例一
任務：針對studentIds5裡的學號一一進行print()
#sequance source
```{r}
studentIds5
```
#body
```{r}
i <- 1 
print(studentIds5[[i]])
```
#for loop
```{r}
for(i in seq_along(studentIds5)){
  print(studentIds5[[i]])
}
```
#範例二
```{r}
gmailAddress <- c(
  "tim@gmail.com",
  "anita",
  "yellen@gmail.com",
  "huang@gmail.com"
)
```
#sequance source
```{r}
gmailAddress
```
#body
```{r}
library(stringr)
i <- 1
if(str_detect(gmailAddress[i],"gmail.com")){
  print(gmailAddress[i])
}else{
  print(str_c(gmailAddress[i],"@gmail.com"))
}
```
#for loop
```{r}
i <-1
for(i in seq_along(gmailAddress)){
  if(str_detect(gmailAddress[i],"gmail.com")){
  print(gmailAddress[i])
}else{
  print(str_c(gmailAddress[i],"@gmail.com"))
}
  
}
```
#作業四
```{r}
load(url("https://www.dropbox.com/s/qnz9paigf61yjus/commitHistory.Rda?raw=1"))
```

print 每個commit 的 author
```{r}
for(i in seq_along(commitHistory)){
  print(commitHistory[[i]]$commit$author$name)
}
```

存下來每個commit的committer
```{r}
for(i in seq_along(commitHistory)){
  print(commitHistory[[i]]$commit$committer$name)
}
```

存下來每個author與committer同人的commitDate
```{r}
for(i in seq_along(commitHistory)){
  if(commitHistory[[i]]$commit$author$name==commitHistory[[i]]$commit$committer$name){
  print(commitHistory[[i]]$commit$committer$date)
  }
}
```
#output
#範例三
將transcriptDataFinal資料中第i個的平均成績算出來並儲存（使用gpa_fun()）


```{r}
saveGPA5 <- vector("numeric",length(studentIds5))
saveGPA5

```
```{r}
saveGPA5 <- vector("numeric",length(studentIds5))
for(i in seq_along(studentIds5)){
gpa_fun(studentIds5[[i]]) -> saveGPA5[[i]]
}
saveGPA5
```
任務一：存下來每個commit的author。

任務二：存下來每個commit的committer。
```{r}
aaw <- vector("character",length(commitHistory))
for(i in seq_along(commitHistory)){
  commitHistory[[i]]$commit$author$name -> aaw[[i]]
}
aaw
```

```{r}
ssa <- vector("character",length(commitHistory))
for(i in seq_along(commitHistory)){
  commitHistory[[i]]$commit$committer$name -> ssa[[i]]
}
ssa
```
```{r}
qqq <- vector("character",length(commitHistory))
for(i in seq_along(commitHistory)){
  if(commitHistory[[i]]$commit$author$name==commitHistory[[i]]$commit$committer$name) {
    commitHistory[[i]]$commit$committer$date -> qqq[[i]]
  }

}
qqq
```

