---
title: "R Notebook"
output: html_notebook
---

```{r}
x5 <- c("台北市","新北市","高雄市")
greatTaipei <- c("台北市","新北市")

x5 %in% greatTaipei

```

```{r}
!(x5 %in% greatTaipei)
```

```{r}
y5 <- c("女","男","女")

y5=="女"

```

```{r}
!(y5=="女")
```

```{r}
x5 %in% greatTaipei
y5=="女"
(x5 %in% greatTaipei) & (y5=="女")
#同時來自大台北又女性
```

```{r}
which((x5 %in% greatTaipei) & (y5=="女"))
```

```{r}
(x5 %in% greatTaipei) | (y5=="女")
```

```{r}
which((x5 %in% greatTaipei) | (y5=="女"))
```

```{r}
xor(x5 %in% greatTaipei, y5=="女")
```

```{r}
which(xor(x5 %in% greatTaipei, y5=="女"))
```

```{r}
library(readr)
exData2 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData2.csv")
date <- as.character(exData2$期間)
currency <- exData2$幣別
exchangeRate <- exData2$匯率
```

請把date的class存成date clas

```{r}
class(date)
```

```{r}
library(lubridate)
date <- ymd(date)
```

```{r}
class(date)
```
1980-08-01之後的資料有多少筆
```{r}
isAfter19800801 <-
  date >= ymd("1980-08-01")
isAfter19800801
```

```{r}
sum(isAfter19800801)
```
幣別為“歐元USD/EUR”的資料有多少筆
```{r}
head(currency)

```

```{r}
head(currency=="歐元USD/EUR")
isEur <- currency=="歐元USD/EUR"
```

```{r}
sum(isEur)
```
有將currency轉乘 factor class
```{r}
currency <- as.factor(currency)
```

```{r}
isEur <- currency=="歐元USD/EUR"
sum(isEur)
```
exchangeRate有多少筆NA
```{r}
isexchangena <- is.na(exchangeRate)
sum(isexchangena)
```
排除NA後，幣別為“歐元USD/EUR”的資料有多少筆
```{r}
isnotNA <- !is.na(exchangeRate)
isnotEur <- currency=="歐元USD/EUR"
```

```{r}
both <- isnotEur & isnotNA
sum(both)
```
另一種方法
```{r}
satisfyboth <- 
  !is.na(exchangeRate) & currency=="歐元USD/EUR"
sum(satisfyboth)
```

```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
courseType <- transcriptDataFinal$`必選修類別（必∕選∕通）`
major <- transcriptDataFinal$學系
studentID <- transcriptDataFinal$學號
grade <- transcriptDataFinal$學期成績
```
有多少筆資料是來自經濟學系
```{r}
sum(major=="經濟學系")
```
請問學號“5bdS6977b”同學修了多少課
```{r}
sum(studentID=="5bdS6977b")
```
請問學號“5bdS6977b”有多少科成績及格
```{r}
sum(
  studentID=="5bdS6977b" & grade>=60
)
```
有多少筆資料來自經濟學系學生且為選修課
```{r}
sum(
  major=="經濟學系" &
    courseType=="選"
)
```
在經濟學系學生且必修課程中，成經不及格佔多少比例
```{r}
sum(
  major=="經濟學系" &
    courseType=="必"
) -> zp
zp

```

```{r}
sum(
  major=="經濟學系" &
    courseType=="必" &
    grade<60
) -> zo
zo
```

```{r}
zo/zp
```

