---
title: '2019-06-05'
author: "Tony"
date: "2019年6月5日"
output: html_document
---
```{r}
utility_cobb_douglass <- function(x,y,.alpha,.beta){
  utilValue <- x^.alpha*y^.beta # 程序產生output值
  return(utilValue) # 傳回output值
}
```
#8.4

```{r}
utility_cobb_douglass(1,2,0.5,0.8)
```

```{r}
utility_cobb_douglass(x=1,y=2,0.5,0.8)
```
#9.1
```{r}
load(url("https://github.com/tpemartin/github-data/blob/master/loopTranscriptData.Rda?raw=true"))
```

```{r}
gpa_fun(transcriptDataFinal$學號[[1]])
```

```{r}
studentID <- unique(transcriptDataFinal$學號)
```
#sequence source
```{r}
# 以前5筆學號為sequence_source
studentIds5 <- studentID[1:5]
studentIds5
```
#作法一
```{r}
for(i in studentIds5){
  print(i) # 印出studentIds5[[i]]
}
```
#作法二
```{r}
for(i in c(1:5)){
  print(i)
  print(studentIds5[[i]]) # 
}
```
#seq_along()依input物件元素個數產生對應的整數向量，相當於c(1:length(input))
#作法三
```{r}
for(i in seq_along(studentIds5)){
  print(studentIds5[[i]])
}
```
#範例二
```{r}
gmailAddress <- c(
  "tim@gmail.com",
  "anita",
  "yellen@gmail.com",
  "huang@gmail.com"
)
```

```{r}
for(i in gmailAddress){
  print(i)
}
```

```{r}
for(i in c(1:4)){
  print(i)
  print(gmailAddress[[i]]) # 
}
```

```{r}
for(i in seq_along(gmailAddress)){
  print(i)
  print(gmailAddress[[i]])
}
```

