---
title: '2019-04-10'
author: "Tony"
date: "2019年4月10日"
output: html_document
---
```{r}
library(stringr)
```


```{r}
course <- c("籃球","棒球","電視")
course
```

```{r}
str_subset(course,"球")
```
表示只把有經濟學三個字的表示出來
```{r}
str_detect(course,"球")
```

```{r}
studentID<-c(
  '410177115','410176080','410174233','410177011','410182045','410176014')
major <- str_sub(studentID,5,6)
major
year <- str_sub(studentID,2,4)
year
```
#5,6代表第五個到第六個
#2,4代表第二到第四個

```{r}
month <- c("3","4","6")
day <- c("11","5","7")
char1 <- c("月","月","月")
char2 <- c("日","日","日")
month
char1
day 
char2
str_c(month,char1,day,char2)
```
#c代表合併
```{r}
str_c(month,c("月"),day,c("日"))
str_c(month,"",day,"日")
```
```{r}
month
day
str_c(month,day, sep="月-")
```

```{r}
dates <- c("3-11", "4-5",  "2-7")
dates
str_split(dates,"-")
```
#splitz用來分割

```{r}
dates
str_replace(dates,"-","月")
```

```{r}
dates2 <- c("3-11-2019", "4-5-2017",  "2-7-2015")
dates2
str_replace(dates2,"-","/")
str_replace_all(dates2,"-","/")
```

```{r}
library(readr)
githubData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/githubData.csv")
username <- githubData$`GitHub username`[11:16]
reponame <- githubData$`GitHub repo name`[11:16]
```

```{r}

str_c("https://github.com",username,reponame,sep="/")
```
or
```{r}
str_c("https://github.com/",username,"/",reponame)
```

#練習一
```{r}
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/%E7%AC%AC%E4%B8%89%E5%B1%86%E7%B6%93%E6%BF%9F%E6%92%AD%E5%AE%A2%E7%AB%B6%E8%B3%BD%E5%8F%83%E8%B3%BD%E4%BD%9C%E5%93%81%E6%8A%95%E7%A5%A8%E7%B5%90%E6%9E%9C%E6%A8%A3%E6%9C%AC%20-%20Sheet1.csv")
birthday<-filmVotingData$`出生西元年月日（驗證本人用）`
```

```{r}
birthday
```

```{r}
 first <-str_sub(birthday,1,4)
second <-str_sub(birthday,5,6)
third <-str_sub(birthday,7,8)
str_c("西元",first,"年",second,"月",third,"日")
```
#練習二
```{r}
years<-c("099/01","099/02","099/03")
```

```{r}
www <- str_split(years,"/")
www
```

```{r}
aaa <- str_sub(www,4,6)
bbb <-str_sub(www,11,12)
aaa2 <- as.integer(aaa)
aaa3 <- aaa2+1911
aaa4 <- as.character(aaa3)
str_c(aaa4,"-",bbb)
```

```{r}
b1<-list("a","b",c(1:10))
typeof(b1)
b1
```

```{r}
b2<-list(
  亦楓="beer",
  第二個="b",
  第三個=c(1:10))
b2
```

