---
title: '2019-03-20'
author: "Tony"
date: "3/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
dialogue <- c("小明說：'明天不用上課。'",
               "小花說：'真的嗎？'")

cat(dialogue, sep="\n")
```

            
                  

```{r}
aLogical <- c(T,TRUE,F,FALSE,FALSE)
class(aLogical)
```

```{r}
sum(aLogical)
```

```{r}
studentMajors <- factor(
  c("經濟系", "經濟系", "法律系")
)
```

```{r}
typeof(studentMajors)
```

```{r}
levels(studentMajors)
```


```{r}
studentMajors <- factor(
  c("經濟系","統計系","法律系")
)
```

```{r}
typeof(studentMajors)
```

```{r}
birthplace <- factor(
  c("台北", "台北", "台中","台中","台中")
)
levels(birthplace)
as.integer(birthplace)
```

```{r}
levels(birthplace)
```

```{r}
stringInteger <- c("1","2")
class(stringInteger)
```

```{r}
birthplace
```

```{r}
trueInteger <- as.integer(stringInteger)
class(trueInteger) # 可以進行數值運算
```

```{r}
library(lubridate)
```

```{r}
time<-ymd_hms("1999-01-01 00:02:53") 
```


```{r}
time<-ymd_hms(
  c("1999-01-01 00:02:53")
   
)
```

```{r}
class(time)
```

```{r}
time
```

```{r}
truetime <- as.integer(time)
class(truetime) 
sum (truetime)
```

```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
```

```{r}
twDateTime
```

```{r}
LondonDateTime <- with_tz(twDateTime,tzone="Europe/London")
```

```{r}
LondonDateTime
```
```{r}
BerlinDateTime <- with_tz(twDateTime,tzone="Europe/Berlin")
```

```{r}
BerlinDateTime
```

```{r}
as.integer(twDateTime)
```


```{r}
as.integer(LondonDateTime)
```

```{r}
twwDateTime <- mdy_hms("4-18-2017 14:04:00", tz="Asia/Taipei")
```

```{r}
twwDateTime
```

```{r}
twwwDateTime <- ymd("2019-03-18", tz="Asia/Taipei")
```

```{r}
twwwDateTime
```

```{r}
tppDateTime <- mdy("March 3,2019", tz="Asia/Taipei")
```

```{r}
tppDateTime
```

```{r}
London2DateTime <- with_tz(twwDateTime,tzone="Europe/London")
```

```{r}
London2DateTime
```

```{r}
as.integer (ymd("1970-01-01"))
as.integer (ymd("1970-01-02")) 
as.integer (ymd("2019-03-11"))
as.integer (ymd("1999-09-14"))
```

```{r}
a <- c(1, 5, -3)
b <- c(0.5, 12, 2)
```

```{r}
a-b
```

```{r}
aL <- c(6L, 5L, -8L)
bL <- c(-2L, -4L, 9L)
```

```{r}
a+bL
```

```{r}
aL-b
```

```{r}
a*b
```

```{r}
a+3
```

```{r}
a^b

```

```{r}

a %% b
```

```{r}
tppDateTime - twDateTime
```

```{r}
twwDateTime- tppDateTime
```

```{r}
startingDate <- ymd("2000-02-17")
```

```{r}
startingDate + years(13)
```

```{r}
startingDate + dyears(14)
```

```{r}
startingDate + days(145)
```

```{r}
startingDate + minutes(1)
```

```{r}
x <- 98
y <- 798
x2 <- c(1,5,10)
y2 <- c(-1,5,20)
```
```{r}

```

```{r}
x>=y
```
```{r}

```

```{r}
x<y
```

```{r}
z=y
z
```

```{r}
x==y
```

```{r}
x2>=y2
```
```{r}
x3 <- c("小明","小花")
y3 <- c("小明","小華")
```

```{r}
x3==y3
```

```{r}
x3!=y3
```

```{r}
x4 <- c(1,5,8)
y4 <- c(5,8)

x4 %in% y4
```

```{r}
y4 %in% x4
```

```{r}
x5 <- c("台北市","新北市","高雄市")
y5 <- c("台北市","新北市")

x5 %in% y5
```

```{r}
x2 <- c(1,NA,10)
y2 <- c(-1,NA,20)

x3 <- c(NA,"小花")
y3 <- c(NA,"小華")
```

```{r}
x2
y2
x2==y2
x3==y3
```

```{r}
is.na(x2)
```

```{r}
is.na(y3)
```

```{r}
sum(x2)
```

```{r}
sum(y2)
```
```{r}
sum(x2)
sum(x2, na.rm = TRUE)
sum(x2,na.rm= F)
```

