---
title: '2019-04-24'
author: "Tony"
date: "2019年4月24日"
output: html_document
---
#matrix
```{r}
Mat1 <- matrix(
  c(1:8),4 ,2
)
Mat1
```

```{r}
class(Mat1)
typeof(Mat1)
```

```{r}
Mat2 <- matrix(
  c("a","b","c","d"), 2, 2
)
Mat2
```

```{r}
class(Mat2)
typeof(Mat2)
```

```{r}
Mat2[[3]]
Mat2[[4]]
Mat2[1,]
Mat2[c(TRUE,TRUE,FALSE,FALSE)]
```

#DATA FRAME
```{r}
StuList <- list(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuList 
```

```{r}
StuDF <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuDF 
```

```{r}
class(StuDF)
typeof(StuDF)
StuDF[[2]][[3]]

```

```{r}
class(StuDF$姓名)


```

```{r}
StuDF$姓名 <- as.character(StuDF$姓名)
class(StuDF$姓名)
```

```{r}
StuDF2 <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50),
  stringsAsFactors = FALSE
  )
StuDF2 

```

```{r}
class(StuDF2$姓名)
```

```{r}
StuList <- list(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuList 
```

```{r}
class(StuList)
as.data.frame(StuList) -> StuDF3

class(StuDF3)
StuDF3

```

```{r}
as.data.frame(StuList,stringsAsFactors = F) -> StuDF4
class(StuDF4)
StuDF4
```

#[.R , .C] object extraction
```{r}
LETTERS # R內設元素值為英文字母群的character vector
chosenLETTERSK <- LETTERS[1:26]

```

```{r}
matObj15 <- matrix(chosenLETTERSK,2,13)
matObj15
tolower(matObj15) -> mj
mj
```

```{r}
matObj15[1,]
matObj15[,8]
mj[2,]
mj[,12]
```
#tolower 轉成大寫
#tpupper 轉成小寫
```{r}
LETTERS # R內設元素值為英文字母群的character vector
chosenLETTERS <- LETTERS[1:15]
matObj1 <- matrix(chosenLETTERS,5,3)
matObj1
```


```{r}
chosenLETTERS[[8]]
matObj1[[8]]
```

```{r}
matObj1
matObj1[3,2] 
matObj1[c(T,F,F,T,F),c(F,TRUE,T)]
matObj1[c(1,4),c(2,3)]
```
#練習題
```{r}
library(readr)
classSurvey <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/classSurvey.csv")
```
取出性別，學分數
```{r}
classSurvey[c(1:60),c(4,5)]
```
取出女性
```{r}
zxcv <- classSurvey$性別=="女"
classSurvey[c(zxcv),]
```

