---
title: '2019-04-17'
author: "Tony"
date: "2019年4月17日"
output: html_document
---

```{r}
library(stringr)
library(lubridate)
```

```{r}
studentRecord <-
  list(
    學號="410073058",
    姓名="王小明",
    性別="男",
    學年平均成績=list(
      一年級=88,
      二年級=90.3,
      三年級=92,
      四年級=95
    )
  )

studentRecord
```

```{r}
plasticContainer <- list(
  Box=c("gun","food"),     # location 1
  Bag=c(78,3,2.5),               # location 2
  Cool=c(FALSE,FALSE,TRUE,TRUE)    # location 3
)
```
#取出其中一個元素
```{r}
plasticContainer
plasticContainer[["Cool"]] 
plasticContainer[[2]]
```
#取出Box的第二個元素
```{r}
ffs <-plasticContainer[["Box"]] 
ffs[[2]]
```

```{r}
ass <- list(成績單 = c(
  個經=90,
  總經=77,
  統計=88)
)
```

```{r}
ffsb <-ass[["成績單"]]
ffsb[[1]]
```

```{r}
studentRecord <-
  list(
    學號="410073058",
    姓名="王小明",
    性別="男",
    學年平均成績=list(
      一年級=88,
      二年級=90.3,
      三年級=92,
      四年級=95
    )
  )

studentRecord
```

```{r}
eet <-studentRecord[["姓名"]]
eet2 <-studentRecord[["學年平均成績"]]
eet
eet2[[3]]
```

```{r}
plasticContainer[c("Box","Cool")] 
plasticContainer[c(1,2)]
```
#用一個中括號的話,取出的元素會和母體一樣
```{r}
zzx <- plasticContainer[c("Box")] 
zzx
zzc <-plasticContainer[["Box"]] 
zzc

```

```{r}
plasticContainer <- list(
  greenBox=c("paper","scissor"),     # location 1
  redBox=c(1,3,2.5),               # location 2
  blueBox=c(TRUE,FALSE,TRUE,TRUE)    # location 3
)
```

```{r}
extract1 <- plasticContainer[c("greenBox")]
extract2 <- plasticContainer[[c("greenBox")]]
```

```{r}
extract1[[1]][[1]]
extract2[[1]]
```

```{r}
length(plasticContainer)
plasticContainer[c(F,F,T)]
```

```{r}
成績單
成績單[c(T,TRUE,F)]
```
#$只能用在LIST
```{r}
plasticContainer
plasticContainer$greenBox
plasticContainer[["greenBox"]]
```

```{r}
ass
ass$成績單
```

```{r}
your_github_username <- "seamonster666"
your_practice_reponame <- "107-2-inclass-practice"
library(httr)
library(stringr)
str_replace_all(
  "https://api.github.com/repos/:owner/:repo/commits",
  c(
    ":owner"=your_github_username,
    ":repo"=your_practice_reponame
    )
  ) -> commitCheckStatement
commitCheck <- content(GET(commitCheckStatement))
commitCheck
```

